@base_url = http://localhost:3000

GET {{base_url}}

#### get reviews & summary for product - if no revs return [] + invalid prod error handling
GET {{base_url}}/api/products/1/reviews

#### summarise reviews - this should check for existing summary & if not exists or expired, generate new summary
POST {{base_url}}/api/products/5/reviews/summarise


#### test no existing reviews error case - should return 404 (pId has no revs in test data)
POST {{base_url}}/api/products/6/reviews/summarise

### get all products
GET {{base_url}}/api/products